### ISSUE TITLE
cannot build on OS X 10.11

### ISSUE THREAD

**Issue by MarloweW** [Shougo/vimproc.vim#253]
```
gcc -O2 -W -Wall -Wno-unused -Wno-unused-parameter -bundle -fPIC -o lib/vimproc_mac.so src/proc.c src/vimstack.c -arch x86_64 -v                                     
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -main-file-name proc.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 264.3.102 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -W -Wall -Wno-unused -Wno-unused-parameter -fdebug-compilation-dir /Users/chichi/.vim/.vim/bundle/vimproc.vim -ferror-limit 19 -fmessage-length 220 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/proc-4075f6.o -x c src/proc.c
clang -cc1 version 7.3.0 (clang-703.0.31) default target x86_64-apple-darwin15.5.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -main-file-name vimstack.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 264.3.102 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -W -Wall -Wno-unused -Wno-unused-parameter -fdebug-compilation-dir /Users/chichi/.vim/.vim/bundle/vimproc.vim -ferror-limit 19 -fmessage-length 220 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/vimstack-c33f5e.o -x c src/vimstack.c
clang -cc1 version 7.3.0 (clang-703.0.31) default target x86_64-apple-darwin15.5.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -bundle -macosx_version_min 10.11.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -o lib/vimproc_mac.so /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/proc-4075f6.o /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/vimstack-c33f5e.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
duplicate symbol _vp_decode_size in:
    /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/proc-4075f6.o
    /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/vimstack-c33f5e.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by k-takata** [comment]
How did you build it?
vimstack.c should not be compiled separately, because it is included in proc.c.

**Comment by MarloweW** [comment]
I just ran `make`. And it tells me 
```
:!make  2>&1| tee /var/folders/pf/mnh01tmd0lndxp7064tfrqlw0000gp/T/vrzcjMo/5
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f make_mac.mak
make[1]: Nothing to be done for `all'.
```

So I ran `gcc -O2 -W -Wall -Wno-unused -Wno-unused-parameter -bundle -fPIC -o lib/vimproc_mac.so src/proc.c src/vimstack.c -arch x86_64 -v` , it gives the error above.

**Comment by Shougo** [comment]
Why you have executed `gcc` by hand?
It is executed automatically by `make`.
What is the problem?

**Comment by k-takata** [comment]
> ```make[1]: Nothing to be done for `all'.```

Wasn't `lib/vimproc_mac.so` already built?

**Comment by MarloweW** [comment]
After running make, vim cann't load vimprc_mac.so, but restart vim fixes this. so I guess it's my mistake.
